/vel_estimation:
  ros__parameters:
    base_link_frame_id: "base_link"
    odom_frame_id: "odom"
    publish_tf: false
    contact_joint_names:
      - L_FOOT_CONTACT
      - R_FOOT_CONTACT
    contact_timeout: 0.03
    contact_debounce: 0.00
    joint_state_timeout: 0.03
    zero_velocity_timeout: 0.5

    vel_std_0: 0.1
    att_std_0: 1.0
    acc_bias_std_0: 0.1
    gyro_bias_std_0: 0.0001
    
    acc_noise_density: 0.001
    gyro_noise_density: 0.001
    acc_bias_random_walk: 0.0001
    gyro_bias_random_walk: 0.0001

    zero_vel_noise_cov: 0.1
    contact_vel_covariance: 0.1