moteus:
  ros__parameters:
    update_rate: 300.0
    joints: ['test1', 'test2']
    # joints: ['LHAA', 'LHFE', 'LKFE']
    test1/can_id: 1
    test1/can_bus: 1
    test2/can_id: 2
    test2/can_bus: 2
    LHAA/can_id: 20
    LHFE/can_id: 21
    LKFE/can_id: 22
