%YAML:1.0

imu0:
  T_i_b:
    - [1.0, 0.0, 0.0, 0.0]
    - [0.0, 1.0, 0.0, 0.0]
    - [0.0, 0.0, 1.0, 0.0]
    - [0.0, 0.0, 0.0, 1.0]
  accelerometer_noise_density: 0.02
  accelerometer_random_walk: 0.0004
  gyroscope_noise_density: 0.01
  gyroscope_random_walk: 8.0e-06
  model: calibrated
  rostopic: /imu/data
  time_offset: 0.0
  update_rate: 100.0
