/capture_point:
  ros__parameters:
    robot_height: 0.57
    t_step: 0.25
    ctrl_time_sec: 0.01
    threshold_next_footstep: 0.1 # Not used
    P_gain_scaling: 0.1
    duration_init_traj: 1.0 # seconds
    safety_radius_CP: 0.4
    T_contact_ignore: 0.1

    r_foot_frame_id: R_FOOT_CONTACT
    r_foot_urdf_frame_id: R_ANKLE
    l_foot_frame_id: L_FOOT_CONTACT
    l_foot_urdf_frame_id: L_ANKLE
    base_link_frame_id: base_link
    offset_baselink_cog_x: 0.02
    offset_baselink_cog_y: 0.002
    offset_baselink_cog_z: 0.0
    time_no_feet_in_contact: 0.2
    foot_separation: 0.1
    swing_x_safe_box_min: -0.3
    swing_x_safe_box_max: 0.3
    swing_y_safe_box_min: -0.4
    swing_y_safe_box_max: 0.4
    swing_z_safe_box_min: -0.1
    swing_z_safe_box_max: 0.3
    walk_slow: False # True if we do walk in place, while holding the robot.
    mode: WALK # options = ['WALK', 'ONE_FOOT_SWING']
    use_adaptive_com: False
    k_I_com: 0.1
