/capture_point:
  ros__parameters:
    robot_height: 0.55
    mass: 8.0 # [kg]
    t_step: 0.5
    ctrl_time_sec: 0.01
    threshold_next_footstep: 0.1 # Not used
    P_gain_scaling: 0.1
    duration_init_traj: 1.0 # seconds
    safety_radius_CP: 0.4
    walk_slow: True # True if we do walk in place, while holding the robot.
    T_contact_ignore: 0.3

    r_foot_frame_id: R_FOOT_CONTACT
    r_foot_urdf_frame_id: R_ANKLE
    l_foot_frame_id: L_FOOT_CONTACT
    l_foot_urdf_frame_id: L_ANKLE
    base_link_frame_id: base_link
    offset_baselink_cog_x: -0.0448709592682471
    offset_baselink_cog_y: 0.0
    offset_baselink_cog_z: 0.0
    time_no_feet_in_contact: 0.2
    foot_separation: 0.1
    half_foot_size: 0.08 # [m]
    swing_x_safe_box_min: -0.3
    swing_x_safe_box_max: 0.3
    swing_y_safe_box_min: -0.4
    swing_y_safe_box_max: 0.4
    swing_z_safe_box_min: -0.1
    swing_z_safe_box_max: 0.3
    mode: STANDING # options = ['WALK', 'STANDING']
