/capture_point:
  ros__parameters:
    robot_height: 0.55
    t_step: 0.25
    ctrl_time_sec: 0.01
    threshold_next_footstep: 0.5
    P_gain_scaling: 0.1
    duration_init_traj: 3.0 # seconds
    safety_radius_CP: 0.4
    T_contact_ignore: 0.1
    r_foot_frame_id: R_FOOT_CONTACT
    l_foot_frame_id: L_FOOT_CONTACT
    base_link_frame_id: base_link